2025-03-15 10:21:52,764 - VigIASystem - INFO - Cargando configuración...
2025-03-15 10:21:52,782 - VigIASystem - INFO - Inicializando base de datos...
2025-03-15 10:21:52,787 - Database - INFO - Base de datos inicializada
2025-03-15 10:21:52,829 - VigIASystem - INFO - Inicializando bus de eventos...
2025-03-15 10:21:54,879 - EventBus - INFO - Conexión exitosa a Redis
2025-03-15 10:21:54,879 - VigIASystem - INFO - Bus de eventos inicializado
2025-03-15 10:21:54,880 - EventBus - INFO - Iniciado listener de mensajes
2025-03-15 10:21:54,880 - VigIASystem - INFO - Inicializando gestor de almacenamiento...
2025-03-15 10:21:54,898 - EventBus - INFO - Suscrito al canal: recording_started
2025-03-15 10:21:54,899 - EventBus - INFO - Suscrito al canal: recording_stopped
2025-03-15 10:21:54,899 - EventBus - INFO - Suscrito al canal: alert_generated
2025-03-15 10:21:54,900 - StorageManager - INFO - Gestor de almacenamiento inicializado
2025-03-15 10:21:54,901 - VigIASystem - INFO - Gestor de almacenamiento inicializado
2025-03-15 10:21:54,901 - VigIASystem - INFO - Inicializando procesadores de video...
2025-03-15 10:21:54,905 - VigIASystem - INFO - Encontradas 0 cámaras
2025-03-15 10:21:54,905 - VigIASystem - INFO - Inicializando manejador de WebSockets...
2025-03-15 10:21:54,906 - EventBus - INFO - Suscrito al canal: alert_*
2025-03-15 10:21:54,906 - EventBus - INFO - Suscrito al canal: camera_*
2025-03-15 10:21:54,907 - EventBus - INFO - Suscrito al canal: detection_*
2025-03-15 10:21:54,907 - EventBus - INFO - Suscrito al canal: system_*
2025-03-15 10:21:54,908 - EventBus - INFO - Suscrito al canal: user_*
2025-03-15 10:21:54,908 - WebSocketEventHandler - INFO - Iniciado manejador de eventos para WebSockets
2025-03-15 10:21:54,908 - VigIASystem - INFO - Sistema vigIA inicializado correctamente
2025-03-15 10:21:54,909 - VigIASystem - INFO - Iniciando procesadores de video...
2025-03-15 10:21:56,963 - VigIASystem - INFO - Sistema vigIA en ejecución
2025-03-15 10:21:59,223 - EventBus - INFO - Conexión exitosa a Redis
2025-03-15 10:21:59,224 - API - INFO - API iniciada correctamente
2025-03-15 10:32:35,865 - Database - ERROR - Error en la transacción: 401: Incorrect username or password
2025-03-15 10:44:25,841 - Database - ERROR - Error en la transacción: 401: Incorrect username or password
2025-03-15 10:44:39,335 - Database - ERROR - Error en la transacción: 401: Incorrect username or password
2025-03-15 10:48:10,941 - Database - ERROR - Error en la transacción: 401: Incorrect username or password
2025-03-15 10:48:14,456 - Database - ERROR - Error en la transacción: 401: Incorrect username or password
2025-03-15 11:15:00,468 - EventBus - INFO - Detenido listener de mensajes
2025-03-15 11:15:00,477 - EventBus - INFO - EventBus cerrado
2025-03-15 11:15:00,478 - API - INFO - API cerrada correctamente
2025-03-15 11:15:00,481 - vigIA - INFO - Recibida señal de terminación
2025-03-15 11:15:00,482 - VigIASystem - INFO - Deteniendo sistema vigIA...
2025-03-15 11:15:00,484 - VigIASystem - INFO - Deteniendo sistema vigIA...
2025-03-15 11:15:00,487 - EventBus - INFO - Detenido listener de mensajes
2025-03-15 11:15:00,487 - StorageManager - INFO - Gestor de almacenamiento cerrado
2025-03-15 11:15:00,488 - EventBus - INFO - Detenido listener de mensajes
2025-03-15 11:15:00,489 - EventBus - INFO - Cancelada suscripción al canal: alert_*
2025-03-15 11:15:00,490 - EventBus - INFO - Cancelada suscripción al canal: camera_*
2025-03-15 11:15:00,490 - EventBus - INFO - Cancelada suscripción al canal: detection_*
2025-03-15 11:15:00,491 - EventBus - INFO - Cancelada suscripción al canal: system_*
2025-03-15 11:15:00,491 - EventBus - INFO - Cancelada suscripción al canal: user_*
2025-03-15 11:15:00,492 - WebSocketEventHandler - INFO - Cerrado manejador de eventos para WebSockets
2025-03-15 11:15:00,493 - EventBus - INFO - Detenido listener de mensajes
2025-03-15 11:15:00,494 - EventBus - INFO - Detenido listener de mensajes
2025-03-15 11:15:00,494 - StorageManager - INFO - Gestor de almacenamiento cerrado
2025-03-15 11:15:00,495 - EventBus - INFO - Detenido listener de mensajes
2025-03-15 11:15:00,495 - WebSocketEventHandler - INFO - Cerrado manejador de eventos para WebSockets
2025-03-15 11:15:00,496 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-37' coro=<VigIASystem.stop() done, defined at E:\IA\motion_detector_clean\src\main.py:200> exception=ConnectionError('Error UNKNOWN while writing to socket. Connection lost.')>
Traceback (most recent call last):
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\connection.py", line 481, in send_packed_command
    await self._writer.drain()
  File "C:\Python312\Lib\asyncio\streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "C:\Python312\Lib\asyncio\streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\IA\motion_detector_clean\src\main.py", line 219, in stop
  File "E:\IA\motion_detector_clean\src\events\event_bus.py", line 235, in close
    await self.stop_listener()
  File "E:\IA\motion_detector_clean\src\events\event_bus.py", line 179, in stop_listener
    await self.pubsub.unsubscribe(*self.handlers.keys())
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\client.py", line 861, in execute_command
    await self._execute(connection, connection.send_command, *args, **kwargs)
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\client.py", line 902, in _execute
    return await conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\retry.py", line 62, in call_with_retry
    await fail(error)
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\client.py", line 891, in _disconnect_raise_connect
    raise error
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\connection.py", line 505, in send_command
    await self.send_packed_command(
  File "E:\IA\motion_detector_clean\venv\Lib\site-packages\redis\asyncio\connection.py", line 492, in send_packed_command
    raise ConnectionError(
redis.exceptions.ConnectionError: Error UNKNOWN while writing to socket. Connection lost.
2025-03-15 11:15:00,579 - EventBus - INFO - EventBus cerrado
2025-03-15 11:15:00,580 - VigIASystem - INFO - Sistema vigIA detenido
